### ISSUE TITLE
y-axis non-detects

### ISSUE THREAD

**Issue by jerfdurf** [genetique-techno/jeff-plots#2]
y-axis goes negative on plots with all 0 concentrations

**Comment by genetique-techno** [comment]
_DUMB_

**Comment by genetique-techno** [comment]
Y-axis rangemode changed from `normal` to `nonnegative` in https://github.com/genetique-techno/jeff-plots/commit/591d8a0e8b63b1ba9bfa9418fcc0c1681fa8d684

**Comment by genetique-techno** [comment]
Fixed the data points being cut off in 5e49bb1f7c8fa08ee9c52a08a9c6e81bdeea4670
There's still a bit of weirdness in how the grid lines work but let me know if this works for now.

![image](https://user-images.githubusercontent.com/11597055/86064440-18cac480-ba3b-11ea-96f4-20f6dfe2e867.png)
